apiVersion: v1
kind: Secret
metadata:
  name: ${stackname}-database-secret
  namespace: ${namespace}
type: Opaque
data:
  POSTGRES_USER: ${database_user_encoded}
  POSTGRES_PASSWORD: ${database_user_password_encoded}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  ${stackname}-database-ss
  namespace: ${namespace}
  labels:
    app:  ${stackname}-database
spec:
  serviceName: ${stackname}-database
  selector:
    matchLabels:
      app: ${stackname}-database
  replicas: 1
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 25%
    type: RollingUpdate
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  volumeClaimTemplates:
  - metadata:
      name: database-data
    spec:
      storageClassName: ${storage_class}
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 2Gi
  template:
    metadata:
      labels:
        app:  ${stackname}-database
    spec:
      hostname: ${stackname}-database
      containers:
      - name:  ${stackname}-database
        image:  ${database_image}
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
        readinessProbe:
          initialDelaySeconds: 30
          exec:
            command:
              - psql
              - -h
              - localhost
              - -U
              - ${database_user}
              - -c
              - SELECT 1
        envFrom:
        - secretRef:
            name: ${stackname}-database-secret
        ports:
        - containerPort: ${database_port}
          name:  database-port
        volumeMounts:
        - name: database-data
          mountPath: /var/lib/postgresql
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ${stackname}-database
  namespace: ${namespace}
spec:
  selector:
    app: ${stackname}-database
  type: ClusterIP
  ports:
  - name: postgres
    protocol: TCP
    port: ${database_port}
    targetPort: database-port
