apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ${stackname}-resource-role
  namespace: ${namespace}
rules:
- apiGroups: [""]
  resources: ["pods","deployments","services"]
  verbs: ["list","get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${stackname}-resource-sa
  namespace: ${namespace}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${stackname}-resource-binding
  namespace: ${namespace}
roleRef:
  apiGroup: ""
  kind: Role
  name: ${stackname}-resource-role
subjects:
  - kind: ServiceAccount
    name: ${stackname}-resource-sa
    namespace: ${namespace}
---
