apiVersion: v1
kind: Secret
metadata:
  name: ${stackname}-rest-secrets
  namespace: ${namespace}
type: Opaque
data:
  DM_PREFERENCES_PASSWORD: ${dm_preferences_password_encoded}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${stackname}-rest-configmap
  namespace: ${namespace}
data:
  DM_DOCBROKER_PORT: "${dm_docbroker_port}"
  DM_DOCBROKER_HOST: "${stackname}-docbroker-int"
  DM_GR_REGISTRY_REPO: "${dm_gr_registry_repo}"
  DM_REST_PORT: "${dm_rest_port}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  ${stackname}-rest-deployment
  namespace: ${namespace}
  labels:
    app:  ${stackname}-rest
spec:
  selector:
    matchLabels:
      app: ${stackname}-rest
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  ${stackname}-rest
    spec:
      serviceAccountName: ${stackname}-resource-sa
      hostname: ${stackname}-rest
      initContainers:
      - name: ${stackname}-rest-init
        image: alpine/k8s:1.29.4
        command: 
        - sh
        - -c
        - |
          while true; do
            ready=$(kubectl get pods -l app=${DOLLAR}DM_SERVER_NAME -o jsonpath='{.items[*].status.containerStatuses[*].ready}' | grep -c true)
            echo ${DOLLAR}ready pods ready
            if  [ "${DOLLAR}ready" -gt 0 ]; then
              echo "Starting deployment..."
              break
            fi
            echo "Waiting 60 seconds for Content Server Readiness..."
            sleep 60
          done
        env:
          - name: DM_SERVER_NAME
            value: ${stackname}-server
      containers:
      - name:  ${stackname}-rest
        image:  ${dm_rest_image}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
        envFrom:
        - secretRef:
            name: ${stackname}-rest-secrets
        - configMapRef:
            name: ${stackname}-rest-configmap
        ports:
        - containerPort:  ${dm_rest_port}
          name:  http
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ${stackname}-rest
  namespace: ${namespace}
spec:
  selector:
    app: ${stackname}-rest
  ports:
  - port: ${dm_rest_port}
    name: docbroker
    targetPort: http
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${stackname}-rest-route
  namespace: ${namespace}
spec:
  parentRefs:
    - name: koeppster-lan-gateway
      namespace: infrastructure
  hostnames: ["${stackname}-rest.k8s.koeppster.lan"]
  rules:
    backendRefs:
    - name: ${stackname}-rest
      namespace: ${namespace}
      port: ${dm_rest_port}
